### ISSUE TITLE
Please add my proof

### ISSUE THREAD

**Issue by vporton** [mikinty/P-vs-NP#1]
My P=NP proof, yet to be scrutinized for errors:
https://drive.google.com/file/d/16Ws_eZF8f-rn1mFvkIT-UdMdvTwOu4vO/view?usp=drive_link

**Comment by mikinty** [comment]
Cool I will add sometime -- is there a more official website you can upload your proof to? Otherwise I will just use the Google Drive link.

I think ideally you've sent your proof to a larger group as well -- I'd like this website to be that group, but I think realistically maybe me and a few others will see your paper if you leave it just here. Let me know if you eventually submit to a journal or blog.

**Comment by vporton** [comment]
Due to religious discrimination, I didn't finished Bachelor in math. I managed to find a person to add me to arXiv, but soon after this I was removed again without an explanation. So, I can't upload to arXiv. I could upload to viXra, but does it make sense.

I think, Google Drive suits the most.

BTW, will you check my proof for errors?

**Comment by mikinty** [comment]
Yes I will read the proof 

Google Drive is fine

**Comment by mikinty** [comment]
Again, at first glance, you have some very non-standard and vague terminology, as mentioned in the Reddit post as well. It's not even a matter of formal math education, you have to use at least similar terms to what other complexity theorists use, or else your paper is very very hard to read.

**Comment by vporton** [comment]
> you have some very non-standard and vague terminology

for example?

**Comment by mikinty** [comment]
> The proof does not present an efficient NP-complete algorithm, because it is generated as twice running “invertor” algorithm which is known to be hard.

efficient usually means polynomial time, algorithms are not NP-complete, they can be used to solve NP-complete problems. What you are trying to say is the proof doesn't present a poly algorithm to solve an NP-complete problem, in which case 99.99% of people stop reading, because you basically just said you didn't solve anything

what do you mean by hard? There's multiple degrees of hardness.

This is literally the abstract, I've read a bit more into the paper but it's very very difficult to read

**Comment by mikinty** [comment]
These are also completely non-standard ways to define an NP-complete problem

Definition 1. NP-algorithm is an atmost exponential-time algorithm that
solves an NP problem.

Definition 2. NP-complete algorithm is an atmost exponential-time algo-
rithm that solves an NP-complete problem.

What is atmost mean? You need to more formally define these terms

**Comment by vporton** [comment]
> efficient usually means polynomial time

n^100000000000000000000000000 is considered inefficient for practical purposes. I met the distinction between a TCS term "polynomial-time" and general programmer's jargon "efficient" many times, especially in the context of P=NP.

Even assuming my proof is correct, I cannot mine Bitcoin by a polynomial-time NP-complete algorithm, because such algorithms that I know have a very big additive constant.

OK, I will add a footnote explaining that here "efficient" does not mean polynomial-time.

**Comment by vporton** [comment]
> What is atmost mean? You need to more formally define these terms

I will add a footnote.
